// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// group_lasso_cpp
arma::mat group_lasso_cpp(const arma::mat& xtx, const arma::mat& xty, const arma::mat Grp, double lambda, const arma::mat& X0, double eta, int max_iter, double tolerance);
RcppExport SEXP _pen_Opt_Gram_group_lasso_cpp(SEXP xtxSEXP, SEXP xtySEXP, SEXP GrpSEXP, SEXP lambdaSEXP, SEXP X0SEXP, SEXP etaSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xtx(xtxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xty(xtySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Grp(GrpSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(group_lasso_cpp(xtx, xty, Grp, lambda, X0, eta, max_iter, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// lasso_row_cpp
arma::rowvec lasso_row_cpp(const arma::mat& xtx, const arma::vec& xty_i, double lambda, const arma::rowvec& x0, bool weak, int max_iter, double tolerance);
RcppExport SEXP _pen_Opt_Gram_lasso_row_cpp(SEXP xtxSEXP, SEXP xty_iSEXP, SEXP lambdaSEXP, SEXP x0SEXP, SEXP weakSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xtx(xtxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xty_i(xty_iSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< bool >::type weak(weakSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(lasso_row_cpp(xtx, xty_i, lambda, x0, weak, max_iter, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pen_Opt_Gram_group_lasso_cpp", (DL_FUNC) &_pen_Opt_Gram_group_lasso_cpp, 8},
    {"_pen_Opt_Gram_lasso_row_cpp", (DL_FUNC) &_pen_Opt_Gram_lasso_row_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_pen_Opt_Gram(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
