# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
group_lasso_cpp <- function(xtx, xty, Grp, lambda, X0, eta, max_iter = 1000L, tolerance = 1e-6) {
    .Call(`_pen_Opt_Gram_group_lasso_cpp`, xtx, xty, Grp, lambda, X0, eta, max_iter, tolerance)
}

#' @importFrom Rcpp evalCpp
lasso_row_cpp <- function(xtx, xty_i, lambda, x0, weak = FALSE, max_iter = 1000L, tolerance = 1e-6) {
    .Call(`_pen_Opt_Gram_lasso_row_cpp`, xtx, xty_i, lambda, x0, weak, max_iter, tolerance)
}

